In [1]:
import sys 
sys.path.append('E:/Amrita/Subjects/Sem 5/BMSP paper work/Code base/Trainer')

import torch
from torchinfo import summary 
from dataset import DecompositionDataset
from model import CoattentionModel

In [2]:
# save_to_lmdb('LMDB files/output.lmdb', 'Dataset/Sample', 'Dataset/audio_metadata.csv')

In [3]:
data = DecompositionDataset(lmdb_path='E:/Amrita/Subjects/Sem 5/BMSP paper work/Dataset/Final VMD/VMD.lmdb')

In [4]:
data[0]['IMF'].shape, data[0]['Spectrogram'].shape, data[0]['Label'].shape, data[0]['Image Mask'].shape, data[0]['Audio Mask'].shape

(torch.Size([1440, 1024]),
 torch.Size([10, 512, 512]),
 torch.Size([]),
 torch.Size([640]),
 torch.Size([1440]))

In [5]:
data[0]['Image Mask'], data[0]['Audio Mask']

(tensor([False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, F

In [11]:
#torch.set_printoptions(profile="full")

for i in data[0]['IMF']:
    print(i)
    
#torch.set_printoptions(profile="default")

tensor([0.0004, 0.0004, 0.0004,  ..., 0.1114, 0.1018, 0.0917])
tensor([ 0.0813,  0.0706,  0.0596,  ..., -0.0645, -0.0379, -0.0110])
tensor([0.0160, 0.0432, 0.0705,  ..., 0.2556, 0.2887, 0.3218])
tensor([0.3546, 0.3871, 0.4193,  ..., 0.1462, 0.1707, 0.1951])
tensor([ 0.2196,  0.2440,  0.2683,  ..., -0.0512, -0.0535, -0.0556])
tensor([-0.0578, -0.0598, -0.0618,  ...,  0.0889,  0.0893,  0.0896])
tensor([0.0899, 0.0902, 0.0905,  ..., 0.2124, 0.1899, 0.1675])
tensor([ 0.1451,  0.1226,  0.1002,  ..., -0.1940, -0.1810, -0.1679])
tensor([-0.1548, -0.1416, -0.1285,  ...,  0.0126,  0.0122,  0.0119])
tensor([0.0116, 0.0112, 0.0109,  ..., 0.3071, 0.3071, 0.3062])
tensor([ 0.3043,  0.3014,  0.2975,  ..., -0.1317, -0.1306, -0.1293])
tensor([-0.1276, -0.1254, -0.1229,  ...,  0.0402,  0.0434,  0.0464])
tensor([ 0.0492,  0.0518,  0.0542,  ..., -0.0028, -0.0027, -0.0027])
tensor([-0.0026, -0.0025, -0.0024,  ...,  0.0007,  0.0007,  0.0006])
tensor([ 0.0006,  0.0006,  0.0005,  ..., -0.0673, -0.0657, -0.06

In [7]:
# from transformers import Wav2Vec2Processor, Wav2Vec2Model

# processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base")
# model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base")

In [8]:
# summary(model)

In [2]:
model = CoattentionModel()

img = torch.rand(4, 10, 512, 512)
audio = torch.rand(4, 1440, 1024)
img_mask = torch.randint(0, 2, (4,640)).type(torch.float32)
audio_mask = torch.randint(0, 2, (4,1440)).type(torch.float32)

summary(model=model,
        input_data=(img, audio, img_mask, audio_mask),
        col_names=['input_size', 'output_size', 'num_params', 'trainable'],
        col_width=20,
        row_settings=['var_names'])

Layer (type (var_name))                                      Input Shape          Output Shape         Param #              Trainable
CoattentionModel (CoattentionModel)                          [4, 10, 512, 512]    [4, 1]               --                   True
├─ImageEncoder (img_encoder)                                 [4, 10, 512, 512]    [4, 640, 1024]       --                   True
│    └─Sequential (patch_conv)                               [4, 10, 512, 512]    [4, 10, 256, 256]    --                   True
│    │    └─Conv2d (0)                                       [4, 10, 512, 512]    [4, 10, 256, 256]    1,610                True
│    │    └─ReLU (1)                                         [4, 10, 256, 256]    [4, 10, 256, 256]    --                   --
│    │    └─BatchNorm2d (2)                                  [4, 10, 256, 256]    [4, 10, 256, 256]    20                   True
│    └─Dropout (dropout)                                     [4, 10, 256, 256]    [4, 10, 256,